fix: add assertion for modified example.md file

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -37,4 +37,13 @@ jobs:
             "urmzd/embed-md:${VERSION}"
       - name: "Assert changes on examples/example.md"
         run: |
+          # assert exit code is 1
           git diff --exit-code examples/example.md
+
+          if [ $? -eq 1 ]; then
+            echo "examples/example.md has been modified"
+            exit 0
+          else
+            echo "examples/example.md has not been modified"
+            exit 1
+          fi
